// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchBunvROUR1g_t3dERc_Xbj_MOSjwhrc',
    appId: '1:598457017881:web:356336f8f59d0c08cf6c88',
    messagingSenderId: '598457017881',
    projectId: 'final-year-project-d8735',
    authDomain: 'final-year-project-d8735.firebaseapp.com',
    databaseURL: 'https://final-year-project-d8735-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-d8735.appspot.com',
    measurementId: 'G-TK7JQR8BB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3AuWOTYBRfngnYFcru6ZnbOu-NVNdgG0',
    appId: '1:598457017881:android:ed4f649dee3fb4cdcf6c88',
    messagingSenderId: '598457017881',
    projectId: 'final-year-project-d8735',
    databaseURL: 'https://final-year-project-d8735-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-d8735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9Yj9TaB5M0suk5AXI4YMlpJtUvUqhBA',
    appId: '1:598457017881:ios:75c6ee6b0bb62494cf6c88',
    messagingSenderId: '598457017881',
    projectId: 'final-year-project-d8735',
    databaseURL: 'https://final-year-project-d8735-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-d8735.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm9Yj9TaB5M0suk5AXI4YMlpJtUvUqhBA',
    appId: '1:598457017881:ios:75c6ee6b0bb62494cf6c88',
    messagingSenderId: '598457017881',
    projectId: 'final-year-project-d8735',
    databaseURL: 'https://final-year-project-d8735-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-d8735.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchBunvROUR1g_t3dERc_Xbj_MOSjwhrc',
    appId: '1:598457017881:web:5841e7fb2c874e7bcf6c88',
    messagingSenderId: '598457017881',
    projectId: 'final-year-project-d8735',
    authDomain: 'final-year-project-d8735.firebaseapp.com',
    databaseURL: 'https://final-year-project-d8735-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-d8735.appspot.com',
    measurementId: 'G-N55M9HB23Y',
  );
}
